### ISSUE TITLE
Queries start failing after some time

### ISSUE THREAD

**Issue by nerandell** [aio-libs/aiopg#67] opened 2015-07-31 03:47 UTC
I am facing an issue where my db queries start failing after sometime. Here is some code that I use to create a pool
```python
class PostgresStore:
    _pool = None
    _connection_params = {}
 
    @classmethod
    def connect(cls, database:str, user:str, password:str, host:str, port:int):
        """
        Sets connection parameters
        """
        cls._connection_params['database'] = database
        cls._connection_params['user'] = user
        cls._connection_params['password'] = password
        cls._connection_params['host'] = host
        cls._connection_params['port'] = port

    @classmethod
    def use_pool(cls, pool:Pool):
        """
        Sets an existing connection pool instead of using connect() to make one
        """
        cls._pool = pool

    @classmethod
    @coroutine
    def get_pool(cls) -> Pool:
        """
        Yields:
            existing db connection pool
        """
        if len(cls._connection_params) < 5:
            raise ConnectionError('Please call SQLStore.connect before calling this method')
        if not cls._pool:
            cls._pool = yield from create_pool(**cls._connection_params)
        return cls._pool
```
I use aiohttp to create a web server and once the server is up and running for a few hours, db quesries start failing. All other apis work perfectly fine. Here are the logs attached:
<pre>
2015-07-14 16:19:18,531 ERROR [base_events:698] Fatal read error on socket transport
protocol: <RequestHandler none:none connected>
transport: <asyncio.selector_events._SelectorSocketTransport object at 0x7f0cb01b8b38>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 459, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2015-07-14 17:26:42,070 ERROR [base_events:698] Fatal error on aiopg connection: bad state in _ready callback
connection: <aiopg.connection.Connection object at 0x7f0cb06756d8>
2015-07-14 17:26:58,017 ERROR [base_events:698] Fatal error on aiopg connection: bad state in _ready callback
connection: <aiopg.connection.Connection object at 0x7f0cb0419128>
2015-07-14 17:27:02,606 ERROR [base_events:698] Fatal error on aiopg connection: bad state in _ready callback
connection: <aiopg.connection.Connection object at 0x7f0cb0413be0>
2015-07-14 17:27:03,226 ERROR [base_events:698] Fatal error on aiopg connection: bad state in _ready callback
connection: <aiopg.connection.Connection object at 0x7f0cb0413780>
2015-07-14 17:27:14,691 ERROR [base_events:698] Fatal error on aiopg connection: bad state in _ready callback
connection: <aiopg.connection.Connection object at 0x7f0cb0413e10>
2015-07-14 18:47:51,427 ERROR [base_events:698] Fatal read error on socket transport
protocol: <RequestHandler none:none connected>
transport: <asyncio.selector_events._SelectorSocketTransport object at 0x7f0cb00c5f98>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 459, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
2015-07-14 18:50:02,499 ERROR [base_events:698] Fatal read error on socket transport
protocol: <RequestHandler none:none connected>
transport: <asyncio.selector_events._SelectorSocketTransport object at 0x7f0cb01f0320>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 459, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
</pre>

**Comment by asvetlov** [comment] 2015-08-13 00:35
Are you sure that error is generated by `aiopg`?
Looks like I've got error from transport but aiopg doesn't use `asyncio` transports at all.

P.S. Please don't use global variables, push aoipg pool into `aiohttp.web.Application`:

    app = aiohttp.web.Application(...)
    app['pgpool'] = yield from aiopg.create_pool(...)

in request handler

   def handler(request):
       pool = request.app['pgpool']

**Comment by nerandell** [comment] 2015-08-13 04:22
I will try that. However, why should declaring a global variable be an issue in the first place though?

**Comment by asvetlov** [comment] 2015-08-13 12:58
No, global variables are not related to your issue.
But as far as I see you *exception traceback* is not related to *aiopg*.

**Comment by bitdancer** [comment] 2015-09-24 14:59
I have a similar situation.  The process works great for extended periods of time, but then suddenly the database connection stops working.  In my log I see only the following:

  2015-09-24 02:04:31,841 asyncio         ERROR    Fatal error on aiopg connection: bad state in _ready callback

I'm giong to be trying to add more error recovery and logging code, so if I learn anything more I'll update.

**Comment by bitdancer** [comment] 2015-09-24 15:10
By the way, I get 10 copies of that message in my log one right after the other.  I presume it is one for each connection in the pool.

**Comment by jettify** [comment] 2015-09-27 17:33
Is any way to reproduce this? We had similar issue with aiomysql due to MySQL server connection timeout, successfully fixed in https://github.com/aio-libs/aiomysql/pull/27

**Comment by bitdancer** [comment] 2015-09-28 13:37
I don't have a reproducer yet, but the data I have so far indicates it is *probably* a result of a timeout on the DB connection.  I'm planning to try to create a reproducer once I have more data.

**Comment by bitdancer** [comment] 2015-10-01 13:34
My case appears to be a consequence of #65.  The reproducer in that issue produces the same kind of traceback that I'm seeing in my applicaion, which I now catch and ignore.  Then 30 seconds later I get the bad state in _ready.

I'll investigate fixing this, but it will probably be a week or more before I can circle back to this problem.

**Comment by pankajnits** [comment] 2015-12-16 17:08
@asvetlov  i was able to reproduce this scenario and basically it was due to timeoutError.
i just ran my test cases on your recent commits and issue no longer exists.

but there is a suggestion https://github.com/aio-libs/aiopg/blob/master/aiopg/connection.py#L182 could you make it to execute in asyncio.sheild() and change cancel() method accordingly, atleast in this case it will ensure that future gets executed properly even if timeout or cancelledError occurs

**Comment by asvetlov** [comment] 2015-12-16 17:13
@pankajnits thanks for good news!

I don't follow your suggestion, sorry.
Cancellation is already executed under the shield. 
Waiting for future object doesn't require shielding, isn't it?

**Comment by pankajnits** [comment] 2015-12-16 17:24
@asvetlov its good that cancel is ensured , but out of curiosity i wanted to ask that what if we can ensure future is shielded irrespective of timeouts.

**Comment by pankajnits** [comment] 2015-12-16 17:30
also will it help in solving https://github.com/aio-libs/aiopg/issues/65

**Comment by pankajnits** [comment] 2015-12-17 04:39
in case of waiter being timedout and scheduled for cancellation, i can see that there are queries in postgres db that are in "idle" state

**Comment by DevSpouk** [comment] 2015-12-28 16:17
Simulate load error. The error manifests itself only when the load increases.
https://gist.github.com/DevSpouk/92a51f2bffb5f6f67352

**Comment by GMLudo** [comment] 2015-12-28 17:48
I've the same issue with a big load when I launch a benchmark on any project based on aiopg.

**Comment by GMLudo** [comment] 2016-01-05 23:29
If somebody has a solution for that, I'm interested in, I'm working for the round 12 of [FrameworkBenchmarks](https://www.techempower.com/benchmarks/).
If I've a solution before Jan 9, I'll push the solution for the round 12.
After, it will be the next round, except if they add more delay.

**Comment by steveholden** [comment] 2016-05-27 11:15
Is this issue still present? We've been looking for an asynchronous wrapper for Posgres acess, but this would probably be a show-stopper.

**Comment by jettify** [comment] 2016-06-01 01:06
Looks like this issue was fixed. @asvetlov could you confirm?

**Comment by asvetlov** [comment] 2016-07-16 15:25
I believe we we have solved the issue.

**Closed by asvetlov** 2016-07-16 15:25 UTC
