### ISSUE TITLE
Default value doesn't work

### ISSUE THREAD

**Issue by AnderUstarroz** [aio-libs/aiopg#49] opened 2015-03-06 19:30 UTC
I've found an unexpected behavior in SQLAlchemy. I'm using the following versions:
- **SQLAlchemy** (0.9.8)
- **PostgreSQL** (9.3.5)
- **psycopg2** (2.5.4)
- **aiopg** (0.5.1)

This is the table definition for the example:

```
import asyncio
from aiopg.sa import create_engine
from sqlalchemy import (
  MetaData,
  Column,
  Integer,
  Table,
  String,
)
metadata = MetaData()

users = Table('users', metadata,
  Column('id_user', Integer, primary_key=True, nullable=False),
  Column('name', String(20), unique=True),
  Column('age', Integer, nullable=False, default=0),
)
```

Now if I try to execute a simple insert to the table just populating the **_id_user**_ and **_name**_, the column **_age**_ should be auto-generated with the default value **0** right? Lets see...

```
@asyncio.coroutine
def go():
  engine = yield from create_engine('postgresql://USER@localhost/DB')
  data = {'id_user':1, 'name':'Jimmy' }
  stmt = users.insert(values=data, inline=False)
  with (yield from engine) as conn:
    result = yield from conn.execute(stmt)


loop = asyncio.get_event_loop()
loop.run_until_complete(go())
```

This is the resulting statement with the corresponding error:

```
INSERT INTO users (id_user, name, age) VALUES (1, 'Jimmy', null);

psycopg2.IntegrityError: null value in column "age" violates not-null constraint
```

I didn't provide the **age** column, so where is that **age = null** value coming from? I was expecting something like this:

```
INSERT INTO users (id_user, name) VALUES (1, 'Jimmy');
```

Or if the **_default**_ flag actually works should be:

```
INSERT INTO users (id_user, name, Age) VALUES (1, 'Jimmy', 0);
```

Could you put some light on this?

**Comment by asvetlov** [comment] 2015-03-06 19:55
Yes, you are right.
aiopg now ignores 'default' argument on data manipulations.
You can use server defaults:

```
        yield from conn.execute('''CREATE TABLE users (
                                            id_user serial PRIMARY KEY,
                                            name varchar(20),
                                            age integer DEFAULT 0)''')
```
or 
```

from sqlalchemy.schema import CreateTable

users = Table('users', metadata,
              Column('id_user', Integer, primary_key=True, nullable=False),
              Column('name', String(20), unique=True),
              Column('age', Integer, nullable=False, server_default='0'))

yield from conn.execute(CreateTable(users))
```

I'll try to fix aiopg to respect `default` argument from table definition.

**Comment by AnderUstarroz** [comment] 2015-03-06 20:12
Thanks @asvetlov  that actually fix the problem!

**Comment by asvetlov** [comment] 2015-04-23 13:48
See also #56

**Comment by serg666** [comment] 2016-04-03 18:04
Hi @asvetlov ! Do You have any news on this issue?

**Comment by AdaJass** [comment] 2016-04-22 13:22
from sqlalchemy.schema import CreateTable

users = Table('users', metadata,
              Column('id_user', Integer, primary_key=True, nullable=False),
              Column('name', String(20), unique=True),
              Column('age', Integer, nullable=False, server_default='0'))

yield from conn.execute(CreateTable(users))

i just for fun, i don't know how to insert code like you do.

**Comment by f0t0n** [comment] 2016-04-22 18:55
Any news on this issue?

The `server_default` won't work in every case.

Say I have a `table_mixin.py` module which defines `onupdate` and `server_onupdate` which don't work at all. So when I execute `UPDATE` query, the `modified_at` doesn't change.

```py
import sqlalchemy as sa


def int_pk():
    return (sa.Column('id', sa.Integer, primary_key=True), )


def timestamp():
    return (
        sa.Column('created_at', sa.DateTime,
                  default=sa.func.current_timestamp(),
                  server_default=sa.func.current_timestamp()),
        sa.Column('modified_at', sa.DateTime,
                  default=sa.func.current_timestamp(),
                  server_default=sa.func.current_timestamp(),
                  onupdate=sa.func.current_timestamp(),
                  server_onupdate=sa.func.current_timestamp()),
    )


def base():
    return int_pk() + timestamp()
```

**Comment by kespindler** [comment] 2016-07-03 15:04
any updates?

**Comment by jettify** [comment] 2016-11-25 22:33
fixed by #206

**Closed by jettify** 2016-11-25 22:33 UTC
Labels: bug

**Comment by serg666** [comment] 2016-11-27 21:52
Guys, what about [Context-Sensitive Default Functions](http://docs.sqlalchemy.org/en/latest/core/defaults.html#context-sensitive-default-functions) ?

For example, I have the following code (from docs example):

`
def mydefault(context):
    return context.current_parameters['counter'] + 12

t = Table('mytable', meta,
    Column('counter', Integer),
    Column('counter_plus_twelve', Integer, default=mydefault, onupdate=mydefault)
)
`

but the problem is **_mydefault_** got sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 instead of sqlalchemy.dialects.postgresql.psycopg2.PGExecutionContext_psycopg2

**Comment by jettify** [comment] 2016-11-28 10:05
@serg666 I do not think we support this feature since we have no tests for this. PR is welcome.

**Comment by mcon** [comment] 2018-04-09 09:56
@jettify Can confirm that the DefaultExecutionContext.get_current_parameters() method no longer exists - is it possible to remove reference to this from the docs? I'm happy to raise a bug / make the appropriate changes myself and PR.
(http://docs.sqlalchemy.org/en/latest/core/defaults.html#context-sensitive-default-functions)

**Comment by jettify** [comment] 2018-04-10 19:09
@mcon please do, any help very appreciated.
