### ISSUE TITLE
close cannot be used while an asynchronous query is underway

### ISSUE THREAD

**Issue by ingmferrer** [aio-libs/aiopg#364] opened 2017-08-01 23:00 UTC
I'm getting this error if I do multiple fetchs. I'm not sure what I'm doing wrong:
```

Exception ignored in: <function ResultProxy.__init__.<locals>.<lambda> at 0x7f979638fe18>
Traceback (most recent call last):
  File "/home/anthbot/Pyvenv/anthbotv5/lib/python3.5/site-packages/aiopg/sa/result.py", line 235, in <lambda>
    self._weak = weakref.ref(self, lambda wr: cursor.close())
  File "/home/anthbot/Pyvenv/anthbotv5/lib/python3.5/site-packages/aiopg/cursor.py", line 50, in close
    self._impl.close()
psycopg2.ProgrammingError: close cannot be used while an asynchronous query is underway
```
This is the query:
```
query = sa.select([role_item]).where(role_item.c.auto_role_id == auto_role_id)
        return await fetch_ite(query)
```
This is the function:
```
async def _fetch(query, type=DBType.ONE):
    async with engine.acquire() as conn:
        res = await conn.execute(query)
        if type == DBType.ONE:
            return await res.fetchone()
        elif type == DBType.ALL:
            return await res.fetchall()
        elif type == DBType.ITE:
            return res
        return None
```

Any help would be appreciated.

**Comment by Skorpyon** [comment] 2017-08-18 18:05
Same issue:

**Comment by DeoLeung** [comment] 2017-09-08 05:13
same here, any hints on what's went wrong?

**Comment by barrachri** [comment] 2017-09-10 01:30
Same problem here.

the problem is that `self._weak = weakref.ref(self, lambda wr: cursor.close())` try to close the connection when a query is underway (as you read from the traceback.

Strange because that line of code is there from a long time:
https://github.com/aio-libs/aiopg/commit/557ad3c2a0fc27c49cb8f973c7c8ccb47ed4615d#diff-e2e6e38bb0fbb338fc152d8f6b75ca37

**Comment by barrachri** [comment] 2017-09-10 10:58
This for me resolve the error

```python
if cursor.description is not None:
            self._metadata = ResultMetaData(self, cursor.description)
            self._weak = None
```
Version of the libraries

```python
aiohttp==2.2.5
aiopg==0.13.0
psycopg2==2.7.3.1
SQLAlchemy==1.1.9
SQLAlchemy-Utils==0.32.14
```

**Comment by Skorpyon** [comment] 2017-10-14 12:09
Any update? Can core developers comment this issue? This exception bore me all time. Please give some advice why its happen and what to do.

**Comment by sajjadalee** [comment] 2017-10-17 07:46
Any update? really tiring my work

**Comment by jettify** [comment] 2017-10-17 07:53
I will take a look, please share script or test case if possible, so I can reproduce locally

**Comment by sajjadalee** [comment] 2017-10-17 12:12
I am trying to run this script : 
https://github.com/mixerp/mixerp/blob/master/src/FrontEnd/db/blank-db.sql

but postgre got stuck. Please replicate it on your machine

Thanks

**Comment by Skorpyon** [comment] 2017-10-17 13:31
@sajjadalee my brain stuck with your script too :D 
Maybe need split it to some readable and understandable parts?
And execute it one by one?
Its amazing, 11Mb SQL querry :D

**Comment by Skorpyon** [comment] 2017-10-17 13:32
I got this exception (close cannot...) with small usual queries like `SELECT blabla, bla FROM blabla WHERE blabla=true;`

**Comment by sajjadalee** [comment] 2017-10-17 14:27
😄  bravo. Its an opensource solution and i wanted to contribute in it. However postgre is such an disappointment so far :(

**Comment by Skorpyon** [comment] 2017-10-17 17:48
@sajjadalee  you may try [asyncpg](https://github.com/MagicStack/asyncpg) or it's SQLAlchemy wrapper  [asyncpgsa](https://github.com/CanopyTax/asyncpgsa), just you need check query timeouts, because your script is giant and may take long time for execution. I have plan move from aiopg to this library, because psycopg async mode disappoint me.

**Comment by jettify** [comment] 2017-10-17 18:49
@sajjadalee That sql script is large, this is not type of workload aiopg is optimized for. Have you tried regula psycopg2 in sync mode?

**Comment by jettify** [comment] 2017-10-17 19:11
Looks like @barrachri is right, basically `ResultProxy` for some reason loose reference tries to close cursor, while original query still executing. One option is to refactor code to use context manager 
https://github.com/aio-libs/aiopg/blob/7d8f58b83b2482de0ef1bfced2d0576e9f8be347/tests/pep492/test_async_await.py#L149-L152
It should explicitly close cursor.

Can anyone test this solution?

**Comment by barrachri** [comment] 2017-10-18 09:56
I'll try to find time later today to test it.

Thanks @jettify

**Comment by pacefalm** [comment] 2017-10-19 13:15
@jettify This appears to have worked for me.

Thanks!

**Comment by jettify** [comment] 2017-10-19 14:41
@asvetlov should we remove code that implicitly closes cursor in order to avoid this issue?

**Comment by barrachri** [comment] 2017-10-19 15:06
It works also for me. 
But I would like to keep the syntax

```python
result = await conn.execute(query)
```

Is there a specific reason to keep track of these weakrefs? 
Shouldn't they garbage collected automatically?

**Comment by LeshkaSafronov** [comment] 2017-11-14 11:38
Hey! I have trouble when using asyncio.gather with cursor and got the same exception.

```
import asyncio
import aiopg
import logging
import random


class Worker:
    def __init__(self):
        self.pool = None
        self.connection_string = 'dbname=aiopg user=aiopg password=passwd host=127.0.0.1'

    async def polygon(self):
        async with self.pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute("""SELECT * from pg_tables WHERE tablename = 'products';""")
                record = await cur.fetchone()
                if not record:
                    await cur.execute("""CREATE TABLE products (
                                            random_number integer
                                         );""")
                await asyncio.gather(*[cur.execute(
                    """
                        INSERT INTO products (random_number) VALUES ({}) RETURNING *;
                    """.format(random.randint(1, 1000))
                ) for _ in range(10)])


    async def start(self):
        self.pool = await aiopg.create_pool(self.connection_string)
        await self.polygon()

worker = Worker()

loop = asyncio.get_event_loop()
loop.run_until_complete(worker.start())
```

Trace:

```Invalid transaction status on released connection: 1
Traceback (most recent call last):
  File "aiopg_test.py", line 26, in polygon
    ) for _ in range(10)])
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/aiopg/cursor.py", line 103, in execute
    waiter = self._conn._create_waiter('cursor.execute')
  File "/usr/local/lib/python3.5/dist-packages/aiopg/connection.py", line 198, in _create_waiter
    'already waiting for incoming data' % func_name)
RuntimeError: cursor.execute() called while another coroutine is already waiting for incoming data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aiopg_test.py", line 36, in <module>
    loop.run_until_complete(worker.start())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "aiopg_test.py", line 31, in start
    await self.polygon()
  File "aiopg_test.py", line 26, in polygon
    ) for _ in range(10)])
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/aiopg/utils.py", line 82, in __aexit__
    self._obj.close()
  File "/usr/local/lib/python3.5/dist-packages/aiopg/cursor.py", line 50, in close
    self._impl.close()
psycopg2.ProgrammingError: close cannot be used while an asynchronous query is underway
Future exception was never retrieved
future: <Future finished exception=OperationalError('Connection closed',)>
psycopg2.OperationalError: Connection closed```


But when I change range(10) to range(1) --> it's OK

aiopg==0.13.1

**Comment by asvetlov** [comment] 2017-11-14 14:05
Hmm.
I'm inclining to keep weakrefs at least until the library will drop `yield from` syntax and use async context managers everywhere.

**Comment by jiujitsu** [comment] 2017-12-04 19:57
Any update on the status of this?

**Comment by asvetlov** [comment] 2017-12-05 06:54
No, we don't perform hidden conversations and secret commits.

**Comment by thehesiod** [comment] 2018-01-04 17:09
btw I got this error while using the aiopg cursor context so that doesn't seem to fix the issue:
```python
  File "/weather/fbn/asyncio/db_utils.py", line 76, in _db_execute
    return cur.rowcount, []
  File "/weather/fbn/asyncio/db_utils.py", line 33, in __aexit__
    return self._ctx.__exit__(exc_type, exc_val, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/aiopg/utils.py", line 220, in __exit__
    self._cur.close()
  File "/usr/local/lib/python3.6/site-packages/aiopg/cursor.py", line 50, in close
    self._impl.close()
psycopg2.ProgrammingError: close cannot be used while an asynchronous query is underway
```

**Comment by jettify** [comment] 2018-01-04 22:32
Issue is strange, any chance you reuse cursor/connection between different coroutines?

**Comment by thehesiod** [comment] 2018-01-04 23:10
@jettify not from what I see, here's what I do:
```python
class _SyncCtxWrapper:
    # wraps an async context around a sync context, need this until https://github.com/aio-libs/aiopg/pull/265 is merged
    def __init__(self, sync_ctx):
        self._ctx = sync_ctx

    async def __aenter__(self):
        return self._ctx.__enter__()

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        return self._ctx.__exit__(exc_type, exc_val, exc_tb)

cursor_ctx = _SyncCtxWrapper(await self._pg_pool.cursor())
async with cursor_ctx as cur:
    await cur.execute(query, parameters)
```

**Comment by thehesiod** [comment] 2018-01-04 23:13
seems like `close` is async, perhaps it's timing out, then it tries to close again and get the error.  Sounds like perhaps it needs to force drop the conn from the pool?

**Comment by AbdullaM5** [comment] 2018-01-06 15:26
Got the same issue in staging environment after 10-15 min in idle, stable reproduce.
aiohttp==2.3.7, aiopg==0.13.2, peewee==2.10.2, peewee-async==0.5.10

**Comment by thehesiod** [comment] 2018-01-07 20:17
@AbdullaM5 could you try my patch in #415 to see if it helps? In my situation once I hit this error my aiopg pool was stuck.  Also if you could provide a script that can reproduce this with a docker postgres server that would be awesome!

**Comment by runtel** [comment] 2018-01-19 18:30
@thehesiod The patch did not help.

**Comment by jettify** [comment] 2018-01-19 18:42
That patch already released in new aiopg version. Can you show code example that reproduces this issue?

**Comment by ekarlso** [comment] 2018-02-08 12:08
hi, I am getting the same issue on latest git

**Comment by smagafurov** [comment] 2018-02-13 09:16
Same here - "close cannot be used while an asynchronous query is underway" after "TimeoutError"

**Comment by thehesiod** [comment] 2018-02-13 09:30
anyone with a reproducible case?

**Comment by runtel** [comment] 2018-03-15 16:49
Make issue on latest git:

```python
import asyncio
from aiopg.sa import create_engine
import datetime
import sqlalchemy as sa
import random

test_table = sa.Table(
    'test_table', sa.MetaData(),
    sa.Column('va1'),
    sa.Column('va2'),
    sa.Column('va3'),
    sa.Column('va4'),
    sa.Column('va5'),
    sa.Column('va6'),
    sa.Column('va7'),
    sa.Column('va8'),
)

create = "CREATE TABLE test_table(" \
         "va1 varchar(100), " \
         "va2 varchar(100), " \
         "va3 varchar(100), " \
         "va4 varchar(100), " \
         "va5 varchar(100), " \
         "va6 varchar(100), " \
         "va7 varchar(100), " \
         "va8 varchar(100))"

select = test_table.select()
insert = test_table.insert().values(
    va1="1edsfsdfasdfasdfasdfadfdsfasdfasdfasdfasdfjhasdlfkhjalskdjhflkajsdhflkasdfasdfasdfd",
    va2="1edsfsdfasdfasdfasdfadfdsfasdfasdfasdfasdfjhasdlfkhjalskdjhflkajsdhflkasdfasdfasdfd",
    va3="1edsfsdfasdfasdfasdfadfdsfasdfasdfasdfasdfjhasdlfkhjalskdjhflkajsdhflkasdfasdfasdfd",
    va4="1edsfsdfasdfasdfasdfadfdsfasdfasdfasdfasdfjhasdlfkhjalskdjhflkajsdhflkasdfasdfasdfd",
    va5="1edsfsdfasdfasdfasdfadfdsfasdfasdfasdfasdfjhasdlfkhjalskdjhflkajsdhflkasdfasdfasdfd",
    va6="1edsfsdfasdfasdfasdfadfdsfasdfasdfasdfasdfjhasdlfkhjalskdjhflkajsdhflkasdfasdfasdfd",
    va7="1edsfsdfasdfasdfasdfadfdsfasdfasdfasdfasdfjhasdlfkhjalskdjhflkajsdhflkasdfasdfasdfd",
    va8="1edsfsdfasdfasdfasdfadfdsfasdfasdfasdfasdfjhasdlfkhjalskdjhflkajsdhflkasdfasdfasdfd"
)
drop = "DROP TABLE test_table"

async def sql_insert(engine, insert):
    await asyncio.sleep(random.random())
    async with engine.acquire() as conn:
        rp = await conn.execute(select)
        # res = await rp.fetchall()

    async with engine.acquire() as conn:
        rp = await conn.execute(insert)
        print(rp)
    print(engine.size, engine.freesize)


async def clear(engine):
    async with engine.acquire() as conn:
        try:
            await conn.execute(drop)
        except:
            pass

        await conn.execute(create)


async def aiopg_test(engine):
    for i in range(1, 10001):
        await sql_insert(engine, insert)


async def test():
    engine = await create_engine(
        host="192.168.0.2",
        port=5432,
        database="demo",
        user="user",
        password="pass",
        minsize=1, maxsize=10)
    await clear(engine)

    asyncio.ensure_future(aiopg_test(engine))
    asyncio.ensure_future(aiopg_test(engine))
    asyncio.ensure_future(aiopg_test(engine))
    asyncio.ensure_future(aiopg_test(engine))
    asyncio.ensure_future(aiopg_test(engine))
    asyncio.ensure_future(aiopg_test(engine))
    asyncio.ensure_future(aiopg_test(engine))
    asyncio.ensure_future(aiopg_test(engine))

    await asyncio.sleep(10000)

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
loop.close()

```
If you uncomment the line "res = await rp.fetchall()" the error does not occur.

ProxyResult.fetchall() closing cursor, may be).

**Comment by thehesiod** [comment] 2018-03-15 17:54
@runtel running that script locally on my mac with python 3.6.3, latest released aiopg + psycopg2 and it just hangs.  Perhaps want to create a docker container with it?

**Comment by runtel** [comment] 2018-03-15 18:08
@thehesiod Engine connect to database? I was running script on same environment(mac + python 3.6.4, latest released aiopg + psycopg2).

**Comment by thehesiod** [comment] 2018-03-15 20:01
aha, looks like there's a huge/infinite timeout by default for connect :)  ok re-created!

**Comment by thehesiod** [comment] 2018-03-15 20:12
@runtel so in this example, the exception is happening due to the weakref in the SQ ResultsProxy trying to close the cursor.  If I re-run the the test with maxsize=1 the issue doesn't happen so it appears to be some issue with using multiple connections..digging

**Comment by thehesiod** [comment] 2018-03-15 20:21
@runtel ok figured it out, in this function:
```python
    async with engine.acquire() as conn:
        rp = await conn.execute(insert)
        print(rp)
```
after print, `_PoolAcquireContextManager.__aexit__` is called, which released the connection back to the free pool, after this returns, the weakref's finalizer in `aiopg.sa.result.ResultProxy` (self._weak) is called, trying to close the connection.  Given that the connection was already returned to the pool, it may be in an active execute triggering the error.  Now, how to fix this....obviously having a weakref that does a close sounds really dangerous.  @jettify  for ideas

**Comment by thehesiod** [comment] 2018-03-15 20:27
I think maybe each connection needs to keep track of all the cursors, and then release then when the connection is released back to the pool, with the cursor.close() then becoming a no-op in this case

**Comment by jettify** [comment] 2018-03-15 21:02
Tricky problem. To workaround this issue `aiopg.sa.result.ResultProxy` should be explicitly closed before returning connection.

**Comment by thehesiod** [comment] 2018-03-15 21:03
I'll work on a PR to fix this in aiopg as well.  First updating all my old PRs :)

**Comment by jettify** [comment] 2018-03-15 21:06
I think tracking cursors is good idea, also we should:
1) force one cursor per connection in any given time
2) close or error if previous cursor is not finalized

**Comment by runtel** [comment] 2018-03-16 05:52
I have one more question) When i init many engine.acquire(), aiopg should append new connections to pool. This happening, but "slowly". Try to set maxsize=10.

**Comment by thehesiod** [comment] 2018-03-18 08:07
@runtel sorry not following your last comment, in your example maxsize=10, have another example?

**Comment by thehesiod** [comment] 2018-03-18 08:36
@jettify should we bump to 0.14 as it can change behavior?

**Comment by runtel** [comment] 2018-03-22 08:36
I can make test on production. Is need?

**Comment by kjopek** [comment] 2018-07-31 15:49
This is really important patch also for us. When it will be merged?

**Comment by thehesiod** [comment] 2018-07-31 18:32
all my aiopg PRs have been stuck :(

**Comment by runtel** [comment] 2018-09-18 10:47
Up)

**Comment by nikitagromov** [comment] 2018-10-10 14:46
You should close cursor by calling `cursor.close()` after using `fetchone`.

**Closed** 2018-10-16 20:45 UTC

**Comment by vir-mir** [comment] 2019-03-23 20:59
Dear all. Please see this pull request https://github.com/aio-libs/aiopg/pull/548.
